{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sp.name" . }}-backend
  labels: {{- include "sp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "sp.selector" (dict "ctx" . "component" "backend") | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
