{{- if not .Values.secret.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tt.name" . }}-secret
  labels: {{- include "tt.labels" . | nindent 4 }}
type: Opaque
stringData:
  API_TOKEN: {{ .Values.secret.apiToken | quote }}
{{- end }}
